Feature/10 list category
ncedu-tlt/2021-ux-films-finder pull request #23
Opened 2022-02-17 09:23 UTC by katesavinova

list category

2022-02-17 18:28 UTC, NataliaKly requested changes

2022-02-17 18:28 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.ts
> +}
Мне кажется, или если это удалить ничего не изменится? :) Оно есть, но не видно, чтоб это где-то использовалось

2022-02-17 18:28 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.ts
> +  films$: Subject<FilmsResponseModel | null> = new Subject();
можно убрать null, апи нам его не вернет

2022-02-17 18:28 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.ts
> +  film: FilmModel | undefined;
можно убрать undefined

2022-02-17 18:28 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.ts
> +  pageSizeOptions: number[] = [5, 10, 25, 100];
тут надо оставить только 20, мы же не планируем переключать

2022-02-17 18:28 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.ts
> +    console.log(page.pageIndex);
логи не надо комитить)

2022-02-17 18:28 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.ts
> +  pageEvent?: PageEvent;
не используется, удаляем

2022-02-17 18:28 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.ts
> +  genre = 0;
давай переименуем в genreId, это же все таки ид, а не название жанра

2022-02-17 18:28 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.ts
> +    this.loadFilms$ = this.filmDataService
нужно добавить пайп take(1), чтобы после каждого получения ответа на запрос обзервабл закрылся.
И нужно отписаться перед отправкой запроса если подписка есть
```
this.loadFilms$ && this.loadFilms$.unsubscribe();
this.loadFilms$ = this.filmDataService
...
```
, чтобы предыдущий запрос не выполнялся. Т.е. когда быстро кликаем по кнопке Next Page нужно чтоб не выполнялись запросы, когда страницы уже прокликали, вот так:
![image](https://user-images.githubusercontent.com/36840773/154546331-247b2411-0c07-4d54-8648-b652d74afe6f.png)

2022-02-17 18:28 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.ts
> +      .subscribe((info: FilmsResponseModel | null) => {
null не нужен

2022-02-17 18:28 UTC, NataliaKly commented on apps/ux-films-finder/src/app/services/film-data.service.ts
> +  ): Observable<FilmsResponseModel | null> {
null не нужен

2022-02-17 18:28 UTC, NataliaKly commented on package.json
> +    "angular-localize": "^2.4.0",
это можно убрать

2022-02-18 06:29 UTC, lordever commented on apps/ux-films-finder/src/app/components/category/category.component.html
> +    <div>
дивы без классов лучше не оставлять. Если класса на него не предвидится, то используй ng-container

2022-02-18 08:45 UTC, NataliaKly approved these changes

2022-02-18 08:46 UTC, merged