Feature/16 suggestions list
ncedu-tlt/2021-ux-films-finder pull request #40
Opened 2022-02-28 11:59 UTC by MunisaYuldasheva

2022-03-01 14:09 UTC, NataliaKly requested changes
Надо поправить стили, чтобы список выглядел как на мокапе

2022-03-03 11:34 UTC, lordever commented on apps/ux-films-finder/src/app/components/category/category.component.less
> +  padding: 1%;
общие стили лучше в общем less определять. А то потом будем искать по всему проекту где это оределяется)

2022-03-08 14:59 UTC, lordever commented on apps/ux-films-finder/src/app/components/category/category.component.html
> +      <a routerLink="/details/{{ film?.kinopoiskId }}">
film не будет null внутри цикла, поэтому ? можно убрать

2022-03-16 07:46 UTC, NataliaKly requested changes

2022-03-16 07:46 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/card/card.component.html
>  <div class="card">
надо сделать пулл из майн ветки в твою, в карточку добавилась иконка пола актера.

2022-03-16 07:46 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.html
> +  <div class="category__card">
этот контейнер содержит не одну карточку, а список. Логичнее его назвать category__cards-list

2022-03-16 07:46 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.html
> +    class="category"
у тебя уже есть блок category, стили навешанные на тот блок будут применяться и на пагинатор, т.к. название класса одинаковое. Надо придумывать уникальные имена для элементов содержащих разную информацию, давай назовем category__paginator

2022-03-16 07:46 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.less
> +  padding: 1%;
отступы в процентах лучше вообще не задавать , тем более на все теги сразу) Нам же не нужны сюрпризы на разных размерах экранов

2022-03-16 07:46 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.less
>    & a {
лучше придумать класс этому элементу и обращатся по нему, в БЭМ не рекомендуется использование дочерних селекторов

2022-03-16 07:46 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.html
> +      <a routerLink="/details/{{ film?.kinopoiskId }}">
![image](https://user-images.githubusercontent.com/36840773/158537514-101160ba-371d-4efe-aa47-faa1357fb337.png)
 не совсем получились корректные размеры. Это из-за:
-  паддинга 1%  
- и из-за того что блок ff-card по ширине-высоте 0 х 0 . Надо ему задать display:block, тогда браузер сможет правильно расчитать размер его. 
Чтоб задать класс на тег <ff-card> нужно в тс прописать такую конструкцию:
```
...
export class CardComponent {
  @HostBinding('class.ff-card')   <--- аннотация привязывает класс к тегу
  private hostClass = true;                 <--- меняя тру-фолс можно добавлять или убирать этот класс. Нам нужно только добавить                
 ...
```

2022-03-16 07:46 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/card/card.component.less
>      color: @color-black-00;
там цвет не совсем черный

2022-03-16 07:46 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/card/card.component.less
> +    left: 277px;
это лишнее, уже указан right:0 , позицию слева можно не указывать

2022-03-16 07:46 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/category/category.component.html
> +          [name]="film.nameOriginal"
сюда надо русское название прокинуть если оно есть, если его нет, тогда оригинальное

2022-03-17 18:14 UTC, NataliaKly approved these changes

2022-03-17 18:14 UTC, merged