Feature/9 footer component
ncedu-tlt/2021-ux-films-finder pull request #41
Opened 2022-03-01 14:04 UTC by AnthonyDeadz

2022-03-01 14:34 UTC, NataliaKly requested changes

2022-03-01 14:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/footer/footer.component.html
> +      <svg
Если уж решил вставлять свг код сюда, то давай его хотя бы оптимизируем. Есть онлайн-сервисы для оптимизации свг, они удаляют лишние теги, атрибуты и пробелы, давай каким-нибудь воспользуемся.

2022-03-01 14:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/footer/footer.component.html
> +<!-- <tag class="block-name__element _modifier1 _modifier2"> -->
комментарии не надо оставлять

2022-03-01 14:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/footer/footer.component.html
> +      <a href="#" class="footer__link">Фильмы</a>
ссылки нужно сделать рабочими. У нас уже есть в рутинг модуле список поддерживаемых жанров, нужно добавить ссылки на них сюда, как это в хедере сделано. Если апи поддерживает какой-то жанр, но в рутинг модуле его нет, то можно его добавить.

2022-03-01 14:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/footer/footer.component.html
> +      <a href="#" class="footer__link">Оставить отзыв</a>
вот эти ссылки мы рабочими врядли сделаем, у нас нет такого функционала. Можно либо убрать их, либо заменить на жанры.

2022-03-01 14:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/footer/footer.component.less
> +// @color-gray-66
комментарии не надо оставлять лишние

2022-03-01 14:34 UTC, NataliaKly commented on apps/ux-films-finder/src/assets/images/svg/email.svg
> +<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
А эти иконки нужны? Они же есть в компоненте

2022-03-01 17:17 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/footer/footer.component.html
> +<!-- <tag class="block-name__element _modifier1 _modifier2"> -->
Хорошо, уберу. Я просто думал, что у нас есть конфигурационный файл, который бы сам убрал все комментарии

2022-03-03 07:16 UTC, NataliaKly requested changes

2022-03-03 07:16 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/footer/footer.component.html
> +      <a routerLink="/not-found" class="footer__link">Сериалы</a>
не надо редиректить юзера на 404, это жестоко)) давай уберем нерабочие ссылки, если не собираемся добавлять эти категории

2022-03-03 07:16 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/footer/footer.component.html
> +      <a routerLink="/not-found" class="footer__link">Live TV</a>
убираем или добавляем категорию в рутинг модуль

2022-03-03 07:16 UTC, NataliaKly commented on apps/ux-films-finder/src/app/app.component.html
> +<ff-footer></ff-footer>
Давай футер к низу спустим, если страница по высоте маленькая. Нужно для контейнера где хедер, контент и футер задать флекс в колонку, а для контента флекс-гроу 1, чтоб он максимально по высоте растянулся, тогда он сдвинет собой футер к низу
![image](https://user-images.githubusercontent.com/36840773/156514894-e999803e-851e-4448-a180-7da9fb466e9d.png)

2022-03-03 11:32 UTC, lordever commented on apps/ux-films-finder/src/app/components/footer/footer.component.html
> +      Ⓒ 2022 View.com, Inc. All rights reserved
&copy вместо Ⓒ. Может не везде правильно рисоваться

2022-03-04 14:42 UTC, NataliaKly requested changes

2022-03-04 14:42 UTC, NataliaKly commented on .vscode/settings.json
> +{
а это здесь точно нужно?

2022-03-14 05:52 UTC, NataliaKly approved these changes

2022-03-14 05:52 UTC, merged