feature/18-search-person-components
ncedu-tlt/2021-ux-films-finder pull request #43
Opened 2022-03-04 09:29 UTC by katesavinova

2022-03-04 14:31 UTC, NataliaKly requested changes
немного замечаний)

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/card/card.component.html
> +    </ng-template>
это можно упростить. 
Модификаторы _icon _male _female нигде не используются в лесс, удаляем.
Если убрать модификаторы, то получается что верстка отличается только ключом иконки <mat-icon>male</mat-icon>. Т.е. можно используя тернарный оператор  `{{ а ? б : в }} `  задать ее.
Ну и остается убрать лишние контейнеры, нужен только <ng-container *ngIf="gender !== ''">, а в нем сразу иконка

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +  <ng-container *ngIf="personsInfo">
а если personsInfo не будет? Например ид руками поменяли в урле. 
Надо смотреть что если на запрос пришло 404 или 400, то редиректить на not-found
Нужно добавить метод с обработкой ошибок в наш сервис:
https://angular.io/guide/http#error-handling

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +      <div class="person__details _img">
не должны быть одинаковые элементы вложены друг в друга (за исключением древовидных структур, но это не наш случай). Можно  "person__details _img" переименовать в person__photo , более говорящее название

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +          class="person__details _img _person-img"
здесь опять person__details, заменить надо. И везде ниже. Модификатор нужен для определения состояния отличного от дефолтного. А тут в блоках совсем разного рода информация, логичнее их сделать разными элементами.
Модификатор на этой странице нужен явно для задания цвета иконки пола. Остальное всё выглядит лишним

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +            </ng-template>
давай тут тоже упростим как я писала выше. Класс для модификатора можно тоже по этому же условию прокинуть

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +              </ng-template>
здесь нужно свериться с дизайном, там оба варианта имени представлены, причем если русского варианта не окажется, то нужно на его место записать английский. 
И в целом страницу привести к виду как по дизайну.
![image](https://user-images.githubusercontent.com/36840773/156775928-6c861678-fbb0-455a-b648-d739a446cc3b.png)

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +            </div>
если дата смерти не null , то  вместо "Возраст: 56" можно написать "Дата смерти: 12-12-1212". Место смерти можем не указывать вообще

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +        <div class="person__facts _profession">
здесь опять вложенность одинаковых элементов. Тоже заменяем класс с модификаторами на конкретизированные элементы

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +      <div class="person__facts _spouses">
здесь должна быть проверка на то есть ли у нас массив отношений, инача отрисуется пустой див

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +      <div class="person__facts _fact">
здесь нужна проверка на наличие фактов. Не надо рисовать название если там нет инфы

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +      <div class="person__facts _films">
по классу не понятно это факты или все таки фильмы. Давай конкретизируем название этого элемента, а так же его дочерних

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +              ></ng-template>
не надо надеятся что prettier приведет всё к красивому виду ) Он умеет иногда криво переносить теги. Если он сделал переносы так - надо поправить, он их сохранит и не будет изменять обратно, если увидит, что они и так нормально расставлены. Должен быть один тег на одной строке

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.less
> +      background: #69f0ae;
цвет надо записать в color.less

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.ts
> +    this.activatedRouter.params.subscribe(params => {
нужно добавить take(1) чтоб подписка не висела

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.ts
> +      this.filmDataService
нужно добавить takeUntil чтоб подписка не висела

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.ts
> +  loadPersonInfo(pageIndex: number) {
тип возвращаемого значения забыли указать

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.ts
> +  onSearch() {
тип возвращаемого значения забыли указать

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/models/biography.model.ts
> +  death: null;
почему null ? апи никогда не вернет дату?) там или налл или строка будет

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/models/biography.model.ts
> +export type KinopoiskRequestModel = BiographyModel;
лишнее

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/models/person-info.model.ts
> +export type KinopoiskRequestModel = PersonInfoModel;
лишнее

2022-03-04 14:31 UTC, NataliaKly commented on apps/ux-films-finder/src/app/models/spouses.model.ts
> +export type KinopoiskRequestModel = SpousesModel;
лишнее

2022-03-07 08:16 UTC, NataliaKly requested changes

2022-03-07 08:16 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.html
> +  <form class="search-person__search">
тут такая же ошибка с использованием лишних модификаторов там, где должны быть элементы.
Из-за того что к search-person__search добавлен маржин, а элементов таких несколько - отступ слева получился не 40, а 80 )
Давай в этом файле названия классов поправим тоже

2022-03-07 08:16 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +              class="person__film-nameRu"
1. не надо писать названия классов с использование камэл-кейса
2. если тут может печататься имя и англйское и русское - то в названии класса можно вообще не указывать локаль

2022-03-07 08:16 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +          <div class="person__professionKey">
не надо писать названия классов с использование камэл-кейса

2022-03-07 08:16 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +          <div class="person__nameEn">
не надо писать названия классов с использование камэл-кейса
можно назвать name-original вместо nameEn

2022-03-07 08:16 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +        <div class="person__genres-and-nameRuEn">
не надо писать названия классов с использование камэл-кейса
genres ? может gender? 
можно использовать здесь названия main-info, name-info, name-row

2022-03-07 08:16 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.less
> +    stroke-opacity: 0%;
лишнее

2022-03-07 08:16 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.less
> +  }
это можно упростить 
```
    &:after,
    &:before {
      content: '';
      display: flex;
      width: 73px;
      height: 100%;
      background: url('../../../assets/images/triangles.svg') no-repeat;
    }
    &:before {
      transform: rotate(0.5turn);
    }
  }
```

2022-03-07 08:16 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/person/person.component.less
> +  }
одинаковые элементы на странице можно назвать одним классом. Например все заголовки для информации (Возраст, Дата рождения, Место рождения, Факты, Фильмы и т.п. ) можно назвать person__label-info

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/card/card.component.html
> +  <ng-container *ngIf="gender !== ''">
!!gender

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +            <ng-container *ngIf="personsInfo.sex !== ''">
!!personsInfo.sex

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/card/card.component.html
> +      <mat-icon>{{ gender === 'FEMALE' ? 'female' : 'male' }}</mat-icon>
давай выделим отдельный enum для значений. Будет что то вроде такого
```
enum GenderEnum {
 MALE = "MALE",
 FEMALE = "FEMALE"
} 

//component.ts
gender: GenderEnum 
GENDER: GenderEnum

//component.html
<mat-icon>{{ gender === GENDER.FEMALE ? 'female' : 'male' }}</mat-icon>
```

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +                {{ personsInfo.sex === 'FEMALE' ? 'female' : 'male' }}
тут та же логика, что отписал выше с enum

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +          src="{{ personsInfo?.posterUrl }}"
убери ? у personsInfo, выше уже есть ngIf с проверкой, поэтому тут и внизу можем быть уверены, что personInfo всегда будет

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +              {{ getDate(personsInfo.birthday) }}
вызов функции внутри шаблона - плохая практика. Тем более для таких простых функций. Т.к. на каждое изменение, будет вызываться функция, что повлияет на производительность. Такой кейс вполне можно обработать через пайп

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +                  spousesItem.relation === 'супруга' ? '_female' : '_male'
давай для spousesItem.relation тоже сделаем enum

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +                routerLink="/persons/{{ spousesItem?.personId }}"
spousesItem всегда будет доступной. Проверка на null не нужна

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/person/person.component.html
> +              >{{ filmsItem.nameRu ? filmsItem.nameRu : filmsItem.nameEn }}
filmsItem.nameRu || filmsItem.nameEn

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/person/person.component.ts
> +  public getRole(professionKey: string): string {
для professionKey лучше сделай enum

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/person/person.component.ts
> +        const param = params['id'];
тут сразу сделай преобразование в number

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.html
> +    [length]="total > 100 ? 100 : total"
total || 100

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.html
> +            [name]="person?.nameRu ? person.nameRu : person.nameEn"
1. Ну нежно проверять на null person 
2. person.nameRu || person.nameEn

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.ts
> +        this.loadPersonInfo(1);
что такое 1? Выведи в отдельную переменную

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.ts
> +    this.loadInfo$ && this.loadInfo$.unsubscribe();
Странная работа с observable. Выглядит, что в коде используется только person$ для получения данных, а loadInfo$ можно удалить

2022-03-08 14:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.ts
> +    this.loadInfo$.unsubscribe();
лучше сделать одну переменную destroy$ и везде использовать её через takeUntill(destroy$)
Т.е. observable будет выглядит так:

```
destroy$: Subject<void> = new Subject<void>()

this.loadInfo$ = this.personData
      .getInfoByPersonName(this.search ?? '', pageIndex)
      .pipe(take(1), takeUntil(this.destroy$))
      .subscribe((info: PersonInfoResponseModel) => {
        this.person$.next(info);
      });
      
ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
 }      
```

2022-03-10 08:12 UTC, katesavinova commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.html
> +    [length]="total > 100 ? 100 : total"
api присылает не больше 100, остальные страницы будут пустыми

2022-03-10 11:14 UTC, lordever commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.html
> +    [length]="total > 100 ? 100 : total"
тогда можно просто total оставить

2022-03-10 12:04 UTC, katesavinova commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.ts
> +    this.loadInfo$.unsubscribe();
unsubscribe$ - не подходит? у меня она есть

2022-03-10 12:06 UTC, katesavinova commented on apps/ux-films-finder/src/app/components/search-persons/search-persons.component.html
> +    [length]="total > 100 ? 100 : total"
тогда я смогу переключаться на след страницу, а там пусто

2022-03-11 15:34 UTC, lordever approved these changes

2022-03-11 15:35 UTC, merged