feature/15-search-component
ncedu-tlt/2021-ux-films-finder pull request #44
Opened 2022-03-07 06:27 UTC by Chugunov-d

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/header/header.component.html
> +      <div *ngIf="isShown || desktop === true" class="header__search-content">
можно просто *ngIf="isShown || desktop"

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/header/header.component.ts
> +    window.innerWidth >= 871
871 вынеси в отдельну переменную и назови DESKTOP_SIZE

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/header/header.component.ts
> +      ? ((this.desktop = true), (this.isShown = false))
переделай на обычный if. Тернарник используй в случае присвоения значения переменной. В случае когда меняются несколько переменных, лучше оставить обычный if для простоты

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +  _searchInput = '';
searchInput, без нижнего подчёркивания

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +    (ngModelChange)="getActorFilms()"
а зачем 2 ngModelChange?)

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +  <mat-icon class="search__filter">filter_list</mat-icon>
странное значение filter_list

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +      routerLink="/details/{{ film?.kinopoiskId }}"
film всегда будет в наличии, поэтому ? можно убрать

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +      ><img src="{{ actor?.posterUrl }}" /> {{ actor?.nameEn }}/{{
actor всегда будет в наличии, поэтому ? можно убрать

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +    class="search__input"
можно убрать в названии search

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +.list {
тут ты для всего с классом list задаёшь стилизацию, что не правильн. Задавать общий класс нужно задавать в миксинах и переиспользовать вездде

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +  &__nameEn {
пустые классы можно убрать

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +      .getFilmByKeyWord(this._searchInput, 1)
что такое 1?

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +        console.log(info);
console.log давай уберём

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +  public getListFilms() {
отступ

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +        console.log(info);
console.log убираем

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/services/film-data.service.ts
> +// import * as url from 'url';
комментации удаляем

2022-03-08 14:20 UTC, lordever commented on apps/ux-films-finder/src/app/services/film-data.service.ts
> +    page: number
давай может зададим поведение по умолчанию для page. Чаще будем вызывать со значением "1"

2022-03-08 14:57 UTC, lordever commented on apps/ux-films-finder/src/app/components/header/header.component.less
> +    color: #69f0ae;
цвета у нас задаются в colors.less

2022-03-14 06:45 UTC, NataliaKly requested changes

2022-03-14 06:45 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +    <p *ngIf="searchInput" class="films__second-titleName">Персоны</p>
камел-кейс в названии классов не используют

2022-03-14 06:45 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +        <p class="films__nameRu">{{ film?.nameRu }}</p>
камел-кейс в названии классов не используют

2022-03-14 06:45 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +        <p class="films__nameEn">{{ film?.nameEn }}</p>
камел-кейс в названии классов не используют

2022-03-14 06:45 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +    <p *ngIf="searchInput" class="films__titleName">Фильмы и сериалы</p>
камел-кейс в названии классов не используют

2022-03-14 06:45 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +    class="search__input"
Идеи БЭМ очень хорошо накладываются на компонентный подход Ангулара. Если компонент search, то все элементы этого компонента можно сделать элементами search:
```
search__field, search__input, search__filter
search__suggestions, search__suggestions-list, search__list-title, search__list-item
```
А в файлах less для компонента создается один главный селектор (т.к. у нас есть темы, то два):
```
.search {
    &__field {}
    &__title {}
    &__suggestions {}
}
.theme-dark {
    & .search {
        &__field {}
        &__title {}
        &__suggestions {}
    }
}
```
Если какой-то тег содержит свой класс, то с т.з. бэм он является отдельным блоком и может использоваться в отрыве от родительского компонента. Мы не можем показывать список предложений поиска где-то еще, в отрыве от поиска) Поэтому этот список (films, films__list и т.п.) должен быть частью search. С остальными селекторами таже идея

2022-03-14 06:45 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +      class="films__list-item"
элемент с классом films__list-item в котором рисуется инфа об актере, а не фильме... Названия классов явно надо пересмотреть) Если не хотим создавать два отдельных класса на одинаковые блоки (что бы не копировать стили например), то можно обозвать класс более абстрактно search__suggestion, search__suggestion-item, search__list-item и т.п.

2022-03-14 06:45 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +        console.log(info);
логи убираем)

2022-03-14 06:45 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +      .subscribe((info: FilmActorModel) => {
оператор take нужен. чтоб подписки не плодились и не висели

2022-03-14 06:45 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +        console.log(info);
логи убрать

2022-03-14 06:45 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +      .subscribe((info: FilmKeywordModel) => {
оператор take нужен. чтоб подписки не плодились и не висели

2022-03-14 06:45 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +    (ngModelChange)="getListFilms(); getActorFilms()"
не надо писать в хтмл несколько действий. Если нужно выполнить более одного - лучше вынести в отдельный метод и сделать там всё что нужно

2022-03-14 06:45 UTC, NataliaKly commented on apps/ux-films-finder/src/app/models/actor.model.ts
> +export interface ActorModel {
у нас есть BiographyModel, можно использовать ее

2022-03-16 06:38 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +    class="search__input"
Почему контейнер со списком ответов назван class="search-field" ? Там же нет поля никакого) Еще раз)
1 компонент = 1 блок. Т.е. всё что находится в search.component.html должно быть элементами блока search. Класс самого блока, если он нужен,  можно добавить на хост в тс файле. 
```
<div class="search__field">
  <input class="search__input"  />
  <mat-icon class="search__filter-icon">tune</mat-icon>
</div>

<ng-container class="search__results">
  <mat-list class="search__results-list">
    <p class="search__results-title">Фильмы и сериалы</p>
    <mat-list-item class="search__list-item">
      <img class="search__poster" />
      <div class="search__info">
        <p class="search__name-ru">{{ film?.nameRu }}</p>
        <p class="search__name-en">{{ film?.nameEn }}</p>
      </div>
    </mat-list-item>
    <div class="search__show-more">
      <p class="search__button">Показать все</p>
      <mat-icon class="search__arrow-icon">keyboard_arrow_right</mat-icon>
    </div>

    <p *ngIf="searchInput" class="search-field__results-title">Персоны</p>
    .....
```

2022-03-16 06:44 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +.list {
в less файле компонента search вообще не должно быть стилей других блоков, только search:
```
.search {
    &__field {}
    &__title {}
    &__suggestions {}
}
.theme-dark {
    & .search {
        &__field {}
        &__title {}
        &__suggestions {}
    }
}
```
Описания прочих блоков вместе с search быть не должно:
```
.list { ... }  <---- лишнее
img { ... }   <---- лишнее
.search { ... }
```
Если они есть - значит неправильно задана структура элементов компонента, скорее всего названия подобрать подходящие и сделать их элементами блока, а не отдельными блоками.

2022-03-16 06:50 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +      .getFilmByKeyWord(this._searchInput, 1)
Магические числа в логике оставлять не нужно, потом приходится делать лишние действия чтоб понять что же туда прокинули в метод) Если надо использовать какое-то определенное число, то 

- либо его пишут как константу, ты уже создавал такую DESKTOP_SIZE = 871;

- либо сохраняют его в поле класса, если оно должно меняться потом и используют поле 

```
this.filmDataService
      .getFilmByKeyWord(this._searchInput, this.page)
```

- либо задают дефолтное значение в методе и при вызове число 1 уже не указывают. Вот этот случай как раз у тебя, можно 1 удалить, раз ты добавил дефолтное значение.

2022-03-16 06:53 UTC, NataliaKly requested changes

2022-03-16 06:53 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +        take(1);
не туда take добавил)) почитай что это такое и как его применять https://rxjs.dev/api/operators/take

2022-03-16 06:53 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +        take(1);
не туда take добавил)) почитай что это такое и как его применять https://rxjs.dev/api/operators/take

2022-03-16 06:53 UTC, NataliaKly commented on apps/ux-films-finder/src/app/models/film-keyword.model.ts
> +export type KinopoiskRequestModel = FilmKeywordModel;
лишнее

2022-03-16 06:53 UTC, NataliaKly commented on apps/ux-films-finder/src/app/models/film-actor.model.ts
> +export type KinopoiskRequestModel = FilmActorModel;
лишнее

2022-03-16 06:53 UTC, NataliaKly commented on apps/ux-films-finder/src/app/services/film-data.service.ts
> +    page: number
здесь тоже можно по дефолту 1 сделать и при вызове не указывать его

2022-03-18 07:53 UTC, NataliaKly requested changes
остались не исправленные коментарии + конфликты (надо сделать пулл из майн)

2022-03-29 18:10 UTC, NataliaKly requested changes

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.html
> +          >ДЕТСКИЙ
давай ветаки следить за переносами) Prettier хороший инструмент, но полностью полагаться на него не стоит, код должен быть аккуратным и читаемым.
Допустимым является перенос одной скобки, когда много параметров задано, например:
```
<ff-card
  class="category__card"
  [name]="film.nameRu || film.nameOriginal"
  [rating]="film.ratingImdb"
  [url]="film.posterUrlPreview"
>          ////////  вот тут ОК
</ff-card>
```
А такое не ОК:
```
<a class="header__link" mat-flat-button routerLink="/for-children"
  >ДЕТСКИЙ
</a>
```

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.less
> +  background: #494949;
цвет через переменные нужно задать

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.less
> +  position: absolute;
из за того что хэдер вынесен на другой слой от статичного контента, контент наезжает на него)
![image](https://user-images.githubusercontent.com/36840773/160665302-6a8d4abe-5017-4b3a-8b82-a1febaa95004.png)

Можно контенту задать отступ у контента. Но зачем тут абсолют?) Если хотел оставить хэдер на месте - то это fixed. Абсолют такого эффекта не дает:

![image](https://user-images.githubusercontent.com/36840773/160665871-bde1b81b-f67e-4705-907b-c932d6c893ac.png)

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.less
> +header {
В БЭМ нужно избегать селекторов тегов и идентификаторов. Нужно задать этому тегу класс. 
Можно вообще убрать этот тег и добавить класс прям на `<ff-header> ` тег, добавив HostBinding, как это сделано в карточке: 
```
@HostBinding('class.ff-card')
  private hostClass = true;
```
Но тогда класс header должен иметь этот тег, т.к. он будет началом бэм-компонента. Для текушего элемента с классом header придется придумать название, например header__content

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.less
>    a {
селектор тега заменяем на селектор класса

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.less
> +  hr {
селектор тега заменяем на селектор класса

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.less
> +  & hr {
селекторы тегов меняем на селекторы классов

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.ts
> +  DESKTOP_SIZE = 871;
если это константа должна быть, то нужен модификатор readonly, чтобы ее нельзя было случайно по ошибке  поменять

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.ts
>    searchDisplay() {
Методы должны начинаться с глагола, если search в данном случае рассматривать как глагол, то "найти дисплей" не очень подходящее название метода)   
Можно переименовать например в  toggleSearchVisibility

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/not-found-page/not-found-page.component.less
> +
а зачем тут пустая строка добавилась посреди списка свойств?)

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +      <p *ngIf="searchInput" class="search__results-title-name">
тайтл и нэйм это почти синонимы) Можно оставить что-то одно, например тайтл

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +    >
переносы поправить
(подробности про переносы в одном из комментариев выше)

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +        ><img class="search__poster" src="{{ film?.posterUrlPreview }}" />
переносы поправить
(подробности про переносы в одном из комментариев выше)

после film можно убрать знак вопроса, т.к. в цикл не зайдет выполнение для  элемента массива undefined или null (обсуждали на синкапе). У остальных использований film?. тоже самое

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +          <p class="search__name-en">{{ film?.nameEn }}</p>
нужно ставить условия, т.к. если не окажется имени, то без условий тег p все равно отрисуется. Это может привести к ошибкам отображения на странице, т.к. он даже пустой может занять некоторое пространство и появится лишний отступ (например если задан паддинг - точно займет по высоте размер паддинга).

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +          <p class="search__name-en">{{ actor?.nameEn }}</p>
условия, см. комментарий выше

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +        ><img class="search__poster" src="{{ actor?.posterUrl }}" />
- знаки вопроса, см. комментарий выше
- переносы поправить  (подробности про переносы в одном из комментариев выше)

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +        >
переносы поправить
(подробности про переносы в одном из комментариев выше)

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +.search {
![image](https://user-images.githubusercontent.com/36840773/160672047-023c280c-1232-4640-954f-521a43ed9b59.png)

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.less
>  .header {
![image](https://user-images.githubusercontent.com/36840773/160672233-0434da5d-7269-48d8-a519-1d6448163789.png)

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +    background: white;
цвет через переменную задать

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +  }
пустые селекторы не надо оставлять, лишний код

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +    background: #494949;
цвет через переменную

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +    display: flex !important;
!important - плохо, вот так можно переопределить стиль:
```
  &__results-list-item.mat-list-item {
    display: flex;
  }
```

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +    font-family: sans-serif;
шрифты свои не надо задавать, должен быть один на все приложение, как по макетам

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +    font-size: 13px;
нечетные размеры шрифта лучше не задавать, разные браузеры могут их немного по-разному отрисовать.
Поправь в остальных местах, и вообще размеры нужно брать с макетов

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +    display: inline;
это свойство можно убрать, т.к. элемент является дочерним у флекс-контейнера. Он и так будет в строку выстраиваться

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +      margin-right: -100px;
это свойство примениться с медиаквери выше, его можно не дублировать

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +      border-radius: 10px;
эти свойства примениться с медиаквери выше, их можно не дублировать

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.less
> +      border-radius: 10px;
здесь тоже лишнее можно убрать

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +  constructor(private filmDataService: FilmDataService) {}
давай отступы расставлять в коде, все-таки это более читаемо, когда визуально отделены блоки кода
![image](https://user-images.githubusercontent.com/36840773/160676367-08ff9e64-6ac7-466b-984c-4150ace0a5e4.png)

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/sidenav-list/sidenav-list.component.less
> +    background: #494949;
цвета через переменные задать

2022-03-29 18:10 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/genres-banner/genres-banner.component.less
> +  margin-top: 90px;
отступ надо задавать на весь контент) а то здесь поправил, а контент на других страницах наезжает на хэдер)

2022-04-09 15:34 UTC, NataliaKly requested changes

2022-04-09 15:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.html
> +        <mat-icon class="header__toogle-button" (click)="sidenav.toggle()">
![image](https://user-images.githubusercontent.com/36840773/162579824-3704d0c1-d3d1-4e65-a615-e92234d02cd7.png)
цвет лучше зеленый или белый. Черные иконки на сером не очень видно, особенно тем, у кого зрение плохое)

2022-04-09 15:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.html
> +      <mat-nav-list class="header__navigation">
![image](https://user-images.githubusercontent.com/36840773/162579954-8d071486-dfc4-45a1-a85a-e2c85ded63ca.png)
когда сжали страницу, открыли меню и расширили обратно - меню не пропадает

2022-04-09 15:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/header/header.component.html
> +        <a class="header__link" mat-flat-button routerLink="/news">НОВОСТИ</a>
давай шрифт попробуем переопределить чтоб везде одинаковый был

2022-04-09 15:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +        <p class="search__button" (click)="getActorFilms()">Показать все</p>
это должна быть ссылка на страницу поиска актеров. Если в поиск ввели что-то, например tom, то при клике на  "Показать все" должна открываться страница 
`/search-persons?search=tom`

2022-04-09 15:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +        <p class="search__button" (click)="getListFilms()">Показать все</p>
это должна быть ссылка на страницу поиска фильмов. Tекущая логика неверная, смысла посылать заново запрос чтоб показать три этих же самых элемента - нету. 
Если в поиск ввели что-то, например pirates, то при клике на "Показать все" должна открываться страница
`/search-films?search=pirates`
где будет список карточек фильмов подходящих по названию (когда его сделают, пока там только надпись-заглушка).

2022-04-09 15:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +      <div *ngIf="searchInput" class="search__show-more">
кликабельным должен быть весь этот элемент, а не только надпись. При клике на стрелку сейчас ничего не произойдет, что не очень логично . При наведении нужно подсвечивать другим цветом, можно белым, чтоб страница была более отзывчивой, и тоже не только надпись, но и стрелку

2022-04-09 15:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +          <p *ngIf="film.nameRu !== undefined" class="search__name-ru">
*ngIf="film.nameRu"
Можно просто оставить такую проверку, если там будет не пустая строка, то она будет приведена к тру и условие выполнится

2022-04-09 15:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +          <p *ngIf="film.nameEn !== undefined" class="search__name-en">
*ngIf="film.nameEn"
Можно просто оставить такую проверку, если там будет не пустая строка, то она будет приведена к тру и условие выполнится

2022-04-09 15:34 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +        class="search__results-list-item"
при наведении нужно менять цвет текста, чтоб страница выглядела более отзывчивой на действия пользователя курсором мыши. И курсор pointer .
И шрифт текста поправь, чтоб как везде был, Bellota Text . А то там Roboto рисуется

2022-04-15 14:28 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +  public getListFilms() {
укажи тип для методов

2022-04-15 14:28 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +import { pipe, Subject, take } from 'rxjs';
pipe - лишний импорт

2022-04-15 14:28 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +  public getInfo() {
на каждый набор символов будет запрос поиска, что не хорошо. Добавь задержку с помощью debounceTime

2022-04-15 14:28 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +        ><img class="search__poster" src="{{ actor.posterUrl }}" />
img на следующую строку

2022-04-15 14:28 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +    <mat-icon routerLink="advanced-search" class="search__filter">
сделай закрытие продвинутого поиска при повторном нажатии на иконку

2022-04-15 14:28 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +        routerLink="/details/{{ film.filmId }}"
при переходе на актёра, или фильм, окно поиска нужно закрыть

2022-04-15 14:28 UTC, lordever commented on apps/ux-films-finder/src/app/components/header/header.component.html
> +      <!--<div class="header__user-info">
убери комменты

2022-04-15 14:28 UTC, lordever commented on apps/ux-films-finder/src/app/components/header/header.component.less
> +    /*&__user-info {
комменты везде убрать

2022-04-21 17:13 UTC, NataliaKly requested changes
поправить логику с debounceTime

2022-04-21 17:13 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/search/search.component.ts
> +      .pipe(take(1), debounceTime(1000))
не совсем верная логика с debounceTime, отписала в ЛС

2022-05-19 15:57 UTC, NataliaKly approved these changes

2022-05-19 15:58 UTC, merged