feature/14-video-component
ncedu-tlt/2021-ux-films-finder pull request #47
Opened 2022-03-28 06:14 UTC by Chugunov-d

2022-04-21 13:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +    (ngModelChange)="getListFilms(); getActorFilms()"
так лучше не делать. Во первых на каждое изменение инупта получим запрос, во вторых 2 вызова метода лучше сделать в отдельном общем методе, иначе получается неинтуитивно

2022-04-21 13:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +      routerLink="/details/{{ film?.filmId }}"
фильм не опциональный

2022-04-21 13:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/search/search.component.html
> +        <p class="films__nameRu">{{ actor?.nameRu }}</p>
actor не опциональный

2022-04-21 13:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/video/video.component.ts
> +export class VideoComponent {
ngOnInit есть, но компонент не имплементирует интерфейс

2022-04-21 13:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/video/video.component.ts
> +  link: any;
link: string

2022-04-21 13:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/video/video.component.ts
> +        let isNotExist = true;
только по коду понятно что мы ищем ссылку на youTube. назови лучше isYoutubeLinkNotExist

2022-04-21 13:56 UTC, lordever commented on apps/ux-films-finder/src/app/components/video/video.component.ts
> +        let isNotExist = true;
а ещё можно написать более лаконично используя find для поиска сайта, который содержит YOUTUBE

2022-05-19 08:10 UTC, NataliaKly requested changes
т.к. ветка отведена была не от майн, а от серча, тут куча изменений по серчу. План такой: мержим сначала серч, делаем пулл из майн, решаем конфликты, затем мержим видео

2022-05-20 11:01 UTC, NataliaKly approved these changes

2022-05-20 11:01 UTC, merged