Feature/7 banner component
ncedu-tlt/2021-ux-films-finder pull request #49
Opened 2022-03-28 14:17 UTC by gavlonskaya

2022-03-28 16:52 UTC, NataliaKly requested changes
не пугайся только Х)

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +    <div class="banner__name">
в этом элементе находиться не только имя, но и лэйблы. Лучше его переименовать,  banner__main-info было бы более подходящим для этого элемента

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +      <div class="banner__name-en">{{ film?.nameEn }}</div>
любого из этих блоков может не оказаться, нужно добавить проверку на второй блок, а в первом рисовать nameRu если он есть, если его нет - то nameEn , и banner__name-en тогда не рисовать

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +      <div class="banner__genre">
banner__genres , там же список жанров, а не один жанр

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +        <div *ngFor="let genre of film.genres">
здесь нужен ng-container, лишняя обертка-див не нужен

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +      </div>
Эту табличку лучше сделать не грид, а флекс. Будет меньше стилей и больше гибкости. Нужно обернуть каждую строку  лэйбл-значение в див и сделать эти дивы флекс, и раздвинуть элементы этих дивом по краям с помощью justify-content: space-between;
Тогда не будет жестких колонок и информация будет более гибко переноситься в рамках своей строки
![image](https://user-images.githubusercontent.com/36840773/160433698-f129db8f-9e6a-485f-a2a0-dae58c1be4cb.png)

Т.е. структура будет такая:
```
<div class="banner__description">
    <div class="banner__description-row">
        <div class="banner__description-title">...</div>
        <div class="banner__description-info">
            <div class="banner__rating">...</div>
        </div>
    </div>
    <div class="banner__description-row">
        <div class="banner__description-title">...</div>
        <div class="banner__description-info">...</div>
    </div>
    ...
</div>
```
Заметь, модификаторы _country _year _filmLength можно убрать, стили будут общие для значений и общие для лэйблов

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +    "
это обсуждали на митинге, у тебя в банере стрелки рисоваться должны всегда, т.к. прокрутка цикличная. Ты никогда не дойдешь до конца при пролистывании в одну сторону) Т.е. условия рисования стрелок дизэйбленными не нужны

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +    />
стрелки не такие как в макете, толстые какие то)

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +    [ngClass]="size - 1 === currentSlide ? 'arrow--disabled' : ''"
не нужные условия и названия классов не по бэм, они должны быть частью блока banner

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +  background: black;
цвет на макете не черный у баннера, и цвета надо через переменные задавать, не black и не #abcdef

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +  height: 100%;
100% от чего?) ну по ширине, допустим понятно, займет всю ширину родительского элемента. А высоту он какую должен был занять?) 
Браузер проигнорировал значение высоты, т.к. задать он его конечно не смог, в родительском элементе нет указанного значения, чтоб он применил его в дочернем. 
И кин-слайдер зам задает ширину 100%, если посмотреть 
![image](https://user-images.githubusercontent.com/36840773/160437207-45715615-c41d-4f91-b48a-6e217b8b16bd.png)
Получается, заданные ширина и высота - лишние)

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +  grid-template-columns: 5fr 2fr 3fr;
эти два свойста не должны быть вместе, одно относится к флекс лайауту, второе для построения грид )) Если используем флекс, то грид свойства писать бесполезно, браузер их проигнорирует, раз флекс задан, а не грид. 
И если посмотреть на свойства заданные кин-слайдером, то он сам проставляет флекс , нам нет необходимости его дублировать
![image](https://user-images.githubusercontent.com/36840773/160437674-27049678-da81-4806-8969-c1e48198ffa2.png)

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    position: relative;
position: relative; здесь лишнее, мы никаких дочерних элементов не располагаем относительно этого элемента

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    width: 100%;
![image](https://user-images.githubusercontent.com/36840773/160438439-d2074dd7-b68c-4576-b3d0-a8f4c4272e21.png)
для этого элемента уже указано такое свойство, в кин-слайдер ксс

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    height: 496px;
органичивать высоту не надо, пусть она будет расчитываться исходя из контента. Сколько займет контент - такой и будет высота слайда

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    background: black;
фон достаточно задать один раз, для всего баннера

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    grid-template-columns: 5fr 2fr 3fr;
не надо задавать 2fr для колонки где будет картинка, она явно займет не 2fr, она же определенной ширины. Лучше задать 
`grid-template-columns: auto 296px auto;`
и еще задать области, это пригодится для того чтоб под мобилку перестроить области
```
    grid-template-areas:
      "main poster description";
```
Можно потом сделать для планшетов и мобилок вот так, тогда все влезет без лишних медиаквери:
![image](https://user-images.githubusercontent.com/36840773/160439534-67178fa8-6354-43cf-9038-57c1e964f2e9.png)

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    padding: 24px 80px 24px 80px;
Если значения для верха\низа одинаковые и слева\справа одинаковые, то можно сократить 
padding: 24px 80px;

где первая цифра - верх\низ,  вторая - слева\справа

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    padding-left: 40px;
паддинг уже указан для баннера, еще один отступ от имени не нужен

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    width: 100%;
ширина здесь точно не нужна, элементы грида и так занимают всю ширину

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +  }
здесь же, где определен грид нужно указать пространство между ячейками грида. Тогда не нужно будет указывать отступы от картинки и дескрипшена. 
column-gap: 40px;

вот они , если их задать
![image](https://user-images.githubusercontent.com/36840773/160441023-4d32c68e-605c-4752-9584-1a9f937a78ce.png)

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    width: 85%;
не нужно ограничивать ширину) пусть занимает все место которое ему потребуется. Если нужно пространство для отступа - то нужно задавать отступы явно. Здесь отступ не нужен, т.к. укажем отступ у колонок грида

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    margin-top: 90px;
отступ сверху 40 по макетам

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    line-height: 1.5;
```
font-size: 40px;
line-height: 56px;
```
font-weight: bold; это не нужно, там обычная ширина в макете.
Цвет лучше указать там же где и бэграунд , т.е. всему баннеру. Мы другого цвета текст и не выводим, там по макетам весь текст белый. Поэтому лучше его указать один раз

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    width: 80%;
не нужно ограничивать ширину) пусть занимает все место которое ему потребуется. Если нужно пространство для отступа - то нужно задавать отступы явно. Здесь отступ не нужен, т.к. укажем отступ у колонок грида

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    color: rgb(167, 167, 167);
цвет текста везде белый по макетам

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    font-size: 19px;
```
    font-size: 24px;
    line-height: 32px;
```
лучше нечетные значения шрифта не задавать, разные браузеры могут по разному отобразить начертание текст

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +  &__genre {
&__genres {
тут же список, а не один жанр)

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    width: 90%;
ширина не нужна

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    height: 496px;
```
    width: 296px;
    height: 444px;
```
по макетам

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    display: flex;
если не указано никаких дополнительных флекс-свойств позиционирования при единственном элементе-потомке , то дисплей флекс смысла не имеет) Элемент отрисуется так же, как и блочный.
А вот эти свойства надо указать: 
```
border-radius: 16px;
    box-shadow: 0 5px 5px rgba(0, 0, 0, 0.25),
      1px -1px 8px rgba(0, 0, 0, 0.25);
    overflow: hidden;
```
а то у картинки ни закруглений, ни тени. Свойство overflow: hidden; спрячет уголки картинки, т.к. они будут торчать от тега img

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    height: 90%;
ширина и высота задана у родительского элемента, здесь можно указать 
```
width: 100%;
    height: 100%;
    object-fit: contain;
```
чтобы картинка попробовала уместиться хотя бы по одной оси на 100%

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    margin-left: 48px;
отступ не нужен, т.к. будет задан grid-gap для баннера

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    margin-top: 100px;
это какой-то большой отступ, по макетам точно не 100. И можно его здесь вообще не указывать, зададим для строк отступ сверху 32рх, и для первой строки соответственно он тоже образуется, и таблица сдвинется вниз не намного

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    line-height: 2;
лучше указывать явные значения в рх для этих свойств, чтобы избежать разного начертания в разных браузерах
```
    font-size: 18px;
    line-height: 32px;
```

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    grid-template-rows: 75px 75px 75px 75px 75px;
меняем на флекс-строки, как описано выше в комментарии для хтмл

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +  }
вот этот кусок при переходе на флекс сократиться на 32 строки))

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +.navigation-wrapper {
вот этого элемента я вообще не нашла в хтмл, лишнее?

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +}
нужно переименовать, сделав их элементами banner, см. комментарий в хтмл

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +}
у нас не бывают дизэйбленные стрелки, убираем)

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +.banner {
с мобильными стилями разберемся позже, как для десктопа поправим)

2022-03-28 16:52 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/genre-label/genre-label.component.less
> +  }
вот эти можно убрать. Попробуем по-хорошему расположить элементы в баннере, чтоб не мельчить шрифты и лэйблы

2022-03-31 10:43 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +      <div class="banner__name-en">{{ film?.nameEn }}</div>
Done

2022-03-31 10:44 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +      <div class="banner__genre">
Done

2022-03-31 10:44 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +        <div *ngFor="let genre of film.genres">
Done

2022-03-31 10:44 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +      </div>
Done

2022-03-31 10:44 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +  background: black;
Done

2022-03-31 10:44 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +  height: 100%;
Done

2022-03-31 10:44 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +  grid-template-columns: 5fr 2fr 3fr;
Done

2022-03-31 10:45 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    position: relative;
Done

2022-03-31 10:45 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    width: 100%;
Done

2022-03-31 10:45 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    height: 496px;
Done

2022-03-31 10:45 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    background: black;
Done

2022-03-31 10:45 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    grid-template-columns: 5fr 2fr 3fr;
Done

2022-03-31 10:45 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    padding: 24px 80px 24px 80px;
Done

2022-03-31 10:45 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    padding-left: 40px;
Done

2022-03-31 10:45 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    width: 100%;
Done

2022-03-31 10:45 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +  }
Done

2022-03-31 10:46 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    width: 85%;
Done

2022-03-31 10:46 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    margin-top: 90px;
Done

2022-03-31 10:46 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    line-height: 1.5;
Done

2022-03-31 10:46 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    width: 80%;
Done

2022-03-31 10:46 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    color: rgb(167, 167, 167);
Done

2022-03-31 10:46 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    font-size: 19px;
Done

2022-03-31 10:46 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +  &__genre {
Done

2022-03-31 10:46 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    width: 90%;
Done

2022-03-31 10:46 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    height: 496px;
Done

2022-03-31 10:46 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    display: flex;
Done

2022-03-31 10:47 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    height: 90%;
Done

2022-03-31 10:47 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    margin-left: 48px;
Done

2022-03-31 10:47 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    margin-top: 100px;
Done

2022-03-31 10:47 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    line-height: 2;
Done

2022-03-31 10:47 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +    grid-template-rows: 75px 75px 75px 75px 75px;
Done

2022-03-31 10:47 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +  }
Done

2022-03-31 10:47 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +.navigation-wrapper {
Done

2022-03-31 10:47 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +}
Done

2022-03-31 10:47 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.less
> +}
Done

2022-03-31 10:48 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/genre-label/genre-label.component.less
> +  }
Done

2022-04-07 07:23 UTC, NataliaKly requested changes
немного комментариев + подтяни изменения из main

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +<div class="banner">
компонент film-banner , давай и блок назовем соответствующе

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +              {{ film?.rating | rating }}
film?.rating 
конструкция со знаком вопроса вернет либо значение, либо undefined, если не окажется фильма и не у чего будет брать рейтинг. Поэтому если в пайпе задать string он ругается, что может раз прийти undefined , то указать только string нельзя. 
С другой стороны - мы перебираем фильмы циклом и записываем каждый перебираемый фильм в переменную film. Если в массиве нет элементов или лежит null, то в цикл не зайдет. Т.е. у нас гарантированно будет film и знак вопроса можно убрать. И указать в пайпе string.
Но у нас нет гарантии что film.rating не вернет undefined, потому что может не оказаться уже rating. Нам нужна проверка на то есть ли у нас рейтинг, и поставить ее надо на всю строку, т.к. строка с одним только названием Рейтинг нам не нужна в табличке)

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.ts
> +        console.log(info);
логи не оставляем)

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.ts
> +            let timeout: any;
таймаут это number

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.ts
> +    if (this.slider) this.slider.destroy();
можно сократить 
this.slider?.destroy();

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/app/models/film-banner-response.model.ts
> +export type KinopoiskRequestModel = FilmBannerResponseModel;
лишнее

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/app/models/film-banner.model.ts
> +export type KinopoiskRequestModel = FilmBannerModel;
лишнее. Бездумно копировать то не надо)

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/app/models/film-banner.model.ts
> +export interface FilmBannerModel {
У нас все поля этой модели есть в моделе FilmModel . Дублировать плохо, поэтому можно создать модель FilmBaseModel с этими полями, а модель FilmModel заэкстендить от FilmBaseModel. 
Пример:
```

//было
export interface MyModel {
  a: string;
  b: number;
  c: boolean;
  d: number;
}

export interface MySecondModel {
  a: string;
  c: boolean;
}

//стало

export interface MyBaseModel {
  a: string;
  c: boolean;
}

export interface MyModel extends MyBaseModel {
  b: number;
  d: number;
}
```
Тогда в MyModel  окажется все 4 поля: 2 указаны явно и 2 придут с MyBaseModel

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/app/pipes/pipe.ts
> +export class RatingStrengthPipe implements PipeTransform {
RatingPipe или  RatingValuePipe

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/app/pipes/pipe.ts
> +  transform(str: any): string {
меняем на string, как исправить ошибку описала выше

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/assets/styles/themes/base/common/colors.less
> +@color-comedy: #b21111;
их можно переименовать чтоб начинались с 
@color-genre-
тогда будет понятнее, что они относятся к жанрам, а не к основным цветам темы. И поместить их в конец файла, чтоб не смешивались с основными цветами.

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/assets/styles/themes/base/common/material.less
> +}
мне кажется это лишнее, пагинатора в баннере нет

2022-04-07 07:23 UTC, NataliaKly commented on apps/ux-films-finder/src/assets/styles/themes/dark/common/colors.less
> +@color-pink-cb: #cb4a78;
давай перенесем эти цвета в основную тему

2022-04-07 08:19 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +<div class="banner">
Done

2022-04-07 08:20 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.ts
> +            let timeout: any;
Done

2022-04-07 08:21 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.ts
> +    if (this.slider) this.slider.destroy();
Done

2022-04-07 08:22 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/models/film-banner-response.model.ts
> +export type KinopoiskRequestModel = FilmBannerResponseModel;
Done

2022-04-07 08:23 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/models/film-banner.model.ts
> +export type KinopoiskRequestModel = FilmBannerModel;
Done

2022-04-07 09:20 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/pipes/pipe.ts
> +export class RatingStrengthPipe implements PipeTransform {
Done

2022-04-07 09:27 UTC, gavlonskaya commented on apps/ux-films-finder/src/assets/styles/themes/base/common/colors.less
> +@color-comedy: #b21111;
Done

2022-04-07 09:32 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/models/film-banner.model.ts
> +export interface FilmBannerModel {
Done

2022-04-07 09:32 UTC, gavlonskaya commented on apps/ux-films-finder/src/assets/styles/themes/base/common/material.less
> +}
Done

2022-04-07 09:35 UTC, gavlonskaya commented on apps/ux-films-finder/src/assets/styles/themes/dark/common/colors.less
> +@color-pink-cb: #cb4a78;
Done

2022-04-07 09:43 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.ts
> +        console.log(info);
Done

2022-04-07 12:41 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +              {{ film?.rating | rating }}
Done

2022-04-07 12:41 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/pipes/pipe.ts
> +  transform(str: any): string {
Done

2022-04-09 14:43 UTC, NataliaKly requested changes
нужно сделать пулл из майн

2022-04-09 14:46 UTC, NataliaKly requested changes

2022-04-09 14:46 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +            *ngIf="film.rating && film.filmLength"
а зачем здесь рейтинг проверяем? какое он отношение имеет к строке с продолжительностью фильма?

2022-04-09 17:18 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/banner/film-banner.component.html
> +            *ngIf="film.rating && film.filmLength"
Done

2022-04-09 18:12 UTC, NataliaKly approved these changes

2022-04-09 18:13 UTC, merged