Feature/37 similar films component
ncedu-tlt/2021-ux-films-finder pull request #50
Opened 2022-03-28 14:35 UTC by AnthonyDeadz

2022-03-29 09:02 UTC, NataliaKly requested changes

2022-03-29 09:02 UTC, NataliaKly commented on apps/api/jest.config.js
> +      tsconfig: '<rootDir>/tsconfig.spec.json'
изменения в этом файле не нужны

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/jest.config.js
> +      stringifyContentPathRegex: '\\.(html|svg)$'
изменения в этом файле не нужны

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/screen-gallery/screen-gallery.component.ts
> +    private cdr: ChangeDetectorRef //TODO: ChangeDetectorRef ?
ChangeDetectorRef нужен, что бы обновить отображение компонента, после того, как пришел список картинок. Слайдер отрисуется раньше, чем придет ответ от сервера, поэтому после ответа в ините явно обновляется вью, а после него вызывается сразу апдейт у слайдера.

Комментарий можно убрать )

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +
@import (inline) 'keen-slider/keen-slider.min.css';  забыл, поэтому слайдер выглядит не как слайдер)

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +  height: 650px;
- ширину явно указывать не нужно, она и так будет 100%. 
- а вот ограничить ее нужно, чтоб слайдер не растянулся шире 1600рх
- высоту указывать и ограничивать не нужно

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +  background-color: @color-gray-66;
у этого компонента нет фона, карточки рисуются на темном\светлом фоне в зависимости от включенной темы

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    color: white;
цвета через переменные указываем

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    font-size: 25px;
размер шрифта с мокапа берем

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    overflow: auto; //TODO: overflow: auto?
```
display: flex;
    flex-direction: row;
    width: 100%;
    overflow: auto;
```
эти свойства не нужны, в ксс от слайдера всё что надо задано уже

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +  }
лишнее

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    padding: 20px;
расстояние между элементами слайдера надо через  spacing проперти при создании слайдера

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    box-shadow: 0px 0px 20px black;
у карточки уже стоит тень, еще одна тень не нужна

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    height: 100px;
высоту не нужно ограничивать, пусть будет по контенту

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    height: 10px;
это очень маленький размер для кнопок, трудно будет целится, особенно тем, укого зрение не очень ) хотя бы 16рх

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    background: #c5c5c5;
цвет через переменную и взять с макета, он отличается для светлой и темной темы

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    background: #000;
на эктив цвет должен быть такой же как и на ховер, ховер забыл указать

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.ts
> +        this.slider?.update();
слайдер не обновляется при переключении по фильмам потому, что инит проходит только один раз. Т.е. 

- открыли один фильм, в компонент прокинулся ид
- сходили один раз на бэк с этим ид
- получили ответ, отрисовали слайдер
- ...и всё) больше на бэк не ходим) соответственно компонент не рисует новые картинки

Нужно отслеживать смену ид и посылать на бэкенд запрос и апдейтить слайдер и точки после получения ответа. Это можно сделать если filmId сделать как set\get 
https://angular.io/guide/component-interaction#intercept-input-property-changes-with-a-setter

2022-03-29 09:02 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.ts
> +  public similarFilms$: Subject<BaseFilmsResponseModel> =
вот это мы обсуждали, что вся модель нас не интересует, нам нужно только 10 фильмов. Т.е. это заменяем на массив, и когда получаем эту модель от бэка - там и нужно достать из нее массив и обрезать его. И тогда уже сохранить обрезанный массив в поле.
Ограничение нужно, т.к. не факт, что нам всегда будет приходить 10-15 фильмов. Может на каком-то фильме придет 100 похожих, и тогда страница будет тормозить) Лучше перестраховаться)

2022-03-29 12:13 UTC, AnthonyDeadz commented on apps/api/jest.config.js
> +      tsconfig: '<rootDir>/tsconfig.spec.json'
> изменения в этом файле не нужны

Вернул запятые обратно и в файле ниже тоже. Просто VS Code вдруг начал подчёркивать ошибку, что запятые там не нужны. Не знаю с чем это связано. Он вообще часто так делает то там, то тут

2022-03-29 12:16 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/screen-gallery/screen-gallery.component.ts
> +    private cdr: ChangeDetectorRef //TODO: ChangeDetectorRef ?
> ChangeDetectorRef нужен, что бы обновить отображение компонента, после того, как пришел список картинок. Слайдер отрисуется раньше, чем придет ответ от сервера, поэтому после ответа в ините явно обновляется вью, а после него вызывается сразу апдейт у слайдера.
> 
> Комментарий можно убрать )

Хорошо, примерно понял. Комментарий убрал

2022-03-29 12:20 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +
> @import (inline) 'keen-slider/keen-slider.min.css'; забыл, поэтому слайдер выглядит не как слайдер)

Ага заработало. Теперь костыли не нужны)

2022-03-29 12:25 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +  height: 650px;
> * ширину явно указывать не нужно, она и так будет 100%.
> * а вот ограничить ее нужно, чтоб слайдер не растянулся шире 1600рх
> * высоту указывать и ограничивать не нужно

Хорошо, убрал. Возьмусь за настройку и ограничение размеров под другие устройства когда полностью закончу компонент

2022-03-29 12:47 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +  background-color: @color-gray-66;
> у этого компонента нет фона, карточки рисуются на темном\светлом фоне в зависимости от включенной темы

Фон убрал

2022-03-29 12:47 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    color: white;
> цвета через переменные указываем

Хорошо, изменю везде цвета

2022-03-29 12:51 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    font-size: 25px;
> размер шрифта с мокапа берем

Это получается нужно заменить тег <p> на любой заголовочный тег <h ...> или есть какой-то константный размер, который можно указать?

2022-03-29 13:00 UTC, NataliaKly commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    font-size: 25px;
не обязательно менять тег, хотя конечно тег h там больше бы подошел по семантике. 
по мокапу шрифт 32рх, а не 25) Вообще нечетные значения лучше не задавать шрифтам, разные браузеры по-разному вычисляют куда дорисовать полпикселя)

2022-03-29 13:14 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    overflow: auto; //TODO: overflow: auto?
> ```
> display: flex;
>     flex-direction: row;
>     width: 100%;
>     overflow: auto;
> ```
> 
> эти свойства не нужны, в ксс от слайдера всё что надо задано уже

Хорошо, теперь с импортом слайдера в ксс и без этого всё работает

2022-03-29 13:15 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +  }
> лишнее

Убрал

2022-03-29 13:23 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    padding: 20px;
> расстояние между элементами слайдера надо через spacing проперти при создании слайдера

Хорошо. Я в одном месте буду использовать паддинг чтобы красивее отображалась тень от карточки, но там ссылка не совсем корректно будет ложиться на карточку. В следующем комите будет видно

2022-03-29 13:25 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    box-shadow: 0px 0px 20px black;
> у карточки уже стоит тень, еще одна тень не нужна

Её было очень плохо видно. Я просто сделал тень погуще

2022-03-29 13:38 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    height: 100px;
> высоту не нужно ограничивать, пусть будет по контенту

Убрал

2022-03-29 13:40 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    height: 10px;
> это очень маленький размер для кнопок, трудно будет целится, особенно тем, укого зрение не очень ) хотя бы 16рх

Так или иначе кнопки до сих пор не отрисовываются, не знаю в чём дело

2022-03-29 13:45 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    background: #c5c5c5;
> цвет через переменную и взять с макета, он отличается для светлой и темной темы

Исправил. Не совсем понимаю как подключать тёмную тему к компоненту

2022-03-29 13:45 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    background: #000;
> на эктив цвет должен быть такой же как и на ховер, ховер забыл указать

Добавил ховер

2022-03-29 14:41 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.ts
> +        this.slider?.update();
> слайдер не обновляется при переключении по фильмам потому, что инит проходит только один раз. Т.е.
> 
> * открыли один фильм, в компонент прокинулся ид
> * сходили один раз на бэк с этим ид
> * получили ответ, отрисовали слайдер
> * ...и всё) больше на бэк не ходим) соответственно компонент не рисует новые картинки
> 
> Нужно отслеживать смену ид и посылать на бэкенд запрос и апдейтить слайдер и точки после получения ответа. Это можно сделать если filmId сделать как set\get https://angular.io/guide/component-interaction#intercept-input-property-changes-with-a-setter

Вроде написал как в примере, но всё ещё не работает. Не совсем понимаю идею. Как мне сеттер и геттер помогут обновлять компонент.

2022-03-31 12:11 UTC, AnthonyDeadz commented on apps/ux-films-finder/jest.config.js
> +      stringifyContentPathRegex: '\\.(html|svg)$'
> изменения в этом файле не нужны

Вернул запятые

2022-03-31 12:12 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    font-size: 25px;
> не обязательно менять тег, хотя конечно тег h там больше бы подошел по семантике. по мокапу шрифт 32рх, а не 25) Вообще нечетные значения лучше не задавать шрифтам, разные браузеры по-разному вычисляют куда дорисовать полпикселя)

изменил размер на 32

2022-03-31 12:13 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    height: 10px;
> это очень маленький размер для кнопок, трудно будет целится, особенно тем, укого зрение не очень ) хотя бы 16рх

Исправили. Кнопки отрисовываются

2022-03-31 12:14 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.less
> +    background: #c5c5c5;
С тёмной темой разобрался

2022-04-19 08:06 UTC, NataliaKly requested changes
Сборка упала, нужно исправить ошибку

2022-05-03 13:14 UTC, lordever commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.ts
> +    setTimeout(() => {
а для чего таймаут?

2022-05-03 13:14 UTC, lordever commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.ts
> +        this.dots.length -= 2;
1. можно сразу сделать
this.dots = Array(this.similarFilms.length) - 2
2. Что значит 2? Выведи константу, чтобы было понятно

2022-05-05 07:56 UTC, NataliaKly requested changes

2022-05-05 07:56 UTC, NataliaKly commented on apps/api/jest.config.js
>  };
не надо здесь изменений делать)

2022-05-05 07:56 UTC, NataliaKly commented on apps/ux-films-finder/jest.config.js
> +    '^.+\\.(ts|mjs|js|html)$': 'jest-preset-angular'
не надо здесь изменений делать)

2022-05-05 08:26 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.ts
> +    setTimeout(() => {
Уже не помню на самом деле. Скорее всего идея была в том, что слайдеру нужно дать время прогрузиться, но т.к. он уже прописан в этом хуке, то таймаут тут не нужен. Я убрал его

2022-05-05 08:48 UTC, AnthonyDeadz commented on apps/ux-films-finder/src/app/components/similar-films/similar-films.component.ts
> +        this.dots.length -= 2;
Да получилось, только -2 записал в скобку. Там дело в том, что одна точка соответствует одному фильму, однако в данном случае на одной точке отображаются сразу три фильма, поэтому лишние точки нужно убрать. Поэтому 2 - это две лишние точки (их всегда две). Выведу константу и назову её extraDots

2022-05-18 14:11 UTC, NataliaKly approved these changes

2022-05-18 14:11 UTC, merged