Feature/31 title films list component
ncedu-tlt/2021-ux-films-finder pull request #54
Opened 2022-04-19 08:15 UTC by gavlonskaya

2022-04-19 10:37 UTC, NataliaKly requested changes
отписала в лс, будем упрощать структуру данных жанров

2022-04-21 12:33 UTC, lordever commented on apps/ux-films-finder/src/app/consts/color-title.const.ts
> +export const COLORSTITLE: {
COLORS_TITLE

2022-04-21 12:33 UTC, lordever commented on apps/ux-films-finder/src/app/consts/title-name.const.ts
> +export const COLORSTITLENAME: {
COLORS_TITLE_NAME

2022-04-21 12:46 UTC, lordever commented on apps/ux-films-finder/src/app/components/title-films-list/title-films-list.component.ts
> +import { Component, HostBinding, Input } from '@angular/core';
HostBinding не используешь и идея подсказывает обычно когда импорт не используется. Можешь чистить такие импорты сочетанием ctrl + alt + o в идее

2022-04-21 13:30 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/consts/color-title.const.ts
> +export const COLORSTITLE: {
Done

2022-04-21 13:31 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/consts/title-name.const.ts
> +export const COLORSTITLENAME: {
Done

2022-04-21 13:32 UTC, gavlonskaya commented on apps/ux-films-finder/src/app/components/title-films-list/title-films-list.component.ts
> +import { Component, HostBinding, Input } from '@angular/core';
Done

2022-05-17 16:11 UTC, NataliaKly approved these changes

2022-05-17 16:12 UTC, merged